# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml hatchling.toml* ./
COPY src/ ./src/

# Install build backend and project
RUN pip install --no-cache-dir hatchling && \
    pip install --no-cache-dir .

# Use unbuffered for real-time logging
ENV PYTHONUNBUFFERED=1

# Default command
CMD ["python", "-m", "notion_api_mcp"]
